# Generated by Django 4.2 on 2023-06-22 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('url', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 6, 22, 21, 53, 12, 489225), verbose_name='Creation date')),
                ('visit_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
